name: saturn
channels:
- https://conda.saturncloud.io/pkgs
- rapidsai/label/cuda10.0
- nvidia
- rapidsai
- pytorch
- numba
- defaults
- conda-forge
- saturncloud
dependencies:
- blas=*=mkl
- python=3.7
- numpy
- pandas
- ipywidgets
- matplotlib
- dask=2.8.1
- dask-saturn
- pip
- snowflake-connector-python
- snowflake-sqlalchemy
- scikit-learn
- scipy
- numba
- bokeh
- h5py
- ipykernel
- graphviz
- s3fs
- dash
- dash-bootstrap-components
- dash-core-components
- dash-daq
- dash-html-components
- dash-renderer
- dash-table
- pip
- s3fs
- nltk
- gensim
- wordcloud
- cvxpy
- pyarrow
- fastparquet
- geopandas
- pytorch=1.4.0=py3.7_cuda10.1.243_cudnn7.6.3_0
- torchvision=0.5.0=py37_cu101
- tensorboard=2.1.0
- tensorflow=2.1.0=gpu_py37h7a4bb67_0
- tensorflow-base=2.1.0=gpu_py37h6c5654b_0
- tensorflow-estimator=2.1.0
- cudf
- cuml
- cugraph
- xgboost
- dask-cuda
- dask-cudf
- dask-cuml
- dask-xgboost
- numba
- pyarrow
- snowflake-connector-python
