name: saturn
channels:
- nvidia
- rapidsai
- pytorch
- numba
- defaults
- saturncloud
dependencies:
- blas=*=mkl
- bokeh
- dask-ml
- dask-saturn=0.1.1
- dask-xgboost
- dask=2.20.0
- distributed=2.20.0
- llvmlite=0.32.1
- numba=0.49.1
- numpy
- pandas
- pip
- prefect>0.13.0
- pyarrow
- python=3.7
- rapids=0.14.1=cuda10.1_py37_0
- s3fs
- scikit-learn
- scipy
- pip:
  - prefect-saturn>=0.2.0