channels:
- defaults
- pytorch
- saturncloud
dependencies:
- blas=*=mkl
- python=3.7
- numpy
- pandas
- ipywidgets
- matplotlib
- dask=2.12.0
- distributed=2.12.0
- dask-saturn=0.0.3
- pip
- snowflake-sqlalchemy
- snowflake-connector-python
- scikit-learn
- scipy
- numba
- bokeh
- h5py
- ipykernel
- graphviz
- s3fs
- dash
- dash-bootstrap-components
- dash-core-components
- dash-daq
- dash-html-components
- dash-renderer
- dash-table
- pip
- s3fs
- nltk
- gensim
- wordcloud
- pytorch-cpu
- torchvision-cpu
- tensorflow=2.1.0=mkl_py37h80a91df_0
- cvxpy
- pyarrow
- fastparquet
- geopandas
- prefect
- voila
name: saturn
