apiVersion: v1
kind: Service
metadata:
  labels:
    run: proxy-test
  name: proxy-test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: proxy-test
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: proxy-test
  name: proxy-test
spec:
  containers:
  - image: dockersamples/101-tutorial
    imagePullPolicy: IfNotPresent
    name: web
    ports:
    - containerPort: 80
      protocol: TCP
  - image: proxy-server:test
    imagePullPolicy: IfNotPresent
    name: proxy
    ports:
    - containerPort: 8080
      protocol: TCP
    env:
      - name: PROXY_LISTEN_PORT
        value: "8080"
      - name: PROXY_TARGET_PORT
        value: "80"
      - name: PROXY_FALLBACK_URL
        value: "http://localhost:8888/"
      - name: PROXY_DEBUG
        value: "true"
  dnsPolicy: ClusterFirst
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: mock-auth-server
  name: mock-auth-server
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    run: mock-auth-server
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mock-auth-server
  name: mock-auth-server
spec:
  containers:
  - image: mock-auth-server:test
    imagePullPolicy: IfNotPresent
    name: auth
    ports:
    - containerPort: 8888
      protocol: TCP
  dnsPolicy: ClusterFirst
