apiVersion: v1
kind: Service
metadata:
  labels:
    run: proxy-test
  name: proxy-test
  namespace: main-namespace
spec:
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30787
  selector:
    run: proxy-test
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: proxy-test
  name: proxy-test
  namespace: main-namespace
spec:
  containers:
  - image: proxy-server:test
    imagePullPolicy: IfNotPresent
    name: proxy
    ports:
    - containerPort: 8080
      protocol: TCP
    env:
      - name: PROXY_LISTEN_PORT
        value: "8080"
      - name: PROXY_TARGET_URL
        value: "http://admin-andrewdask-dask.main-namespace:8787"
      - name: PROXY_FALLBACK_URL
        value: "http://192.168.99.100:30888/"
      - name: PROXY_DEBUG
        value: "true"
  dnsPolicy: ClusterFirst
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: mock-auth-server
  name: mock-auth-server
  namespace: main-namespace
spec:
  ports:
  - port: 8888
    protocol: TCP
    nodePort: 30888
  selector:
    run: mock-auth-server
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mock-auth-server
  name: mock-auth-server
  namespace: main-namespace
spec:
  containers:
  - image: mock-auth-server:test
    imagePullPolicy: IfNotPresent
    name: auth
    ports:
    - containerPort: 8888
      protocol: TCP
  dnsPolicy: ClusterFirst
